// Stocks Tracker API
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// The version of the OpenAPI document: 0.1.2
//
// Generated by: https://openapi-generator.tech

use serde::{
    Deserialize,
    Serialize,
};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiveResponse {
    #[serde(rename = "active_id")]
    pub active_id: i32,
    #[serde(rename = "bought_price")]
    pub bought_price: f64,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "security_id")]
    pub security_id: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
}

impl ActiveResponse {
    pub fn new(
        active_id: i32,
        bought_price: f64,
        count: i32,
        currency: String,
        security_id: String,
        user_id: i32,
    ) -> ActiveResponse {
        ActiveResponse {
            active_id,
            bought_price,
            count,
            currency,
            security_id,
            user_id,
        }
    }
}
