// Stocks Tracker API
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// The version of the OpenAPI document: 0.1.2
//
// Generated by: https://openapi-generator.tech

use serde::{
    Deserialize,
    Serialize,
};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginQuery {
    #[serde(rename = "user")]
    pub user: String,
}

impl LoginQuery {
    pub fn new(user: String) -> LoginQuery {
        LoginQuery { user }
    }
}

impl std::fmt::Display for LoginQuery {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.user)
    }
}
