// Stocks Tracker API
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// The version of the OpenAPI document: 0.1.2
//
// Generated by: https://openapi-generator.tech

use serde::{
    Deserialize,
    Serialize,
};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PingResponse {
    #[serde(rename = "status_code")]
    pub status_code: i32,
}

impl PingResponse {
    pub fn new(status_code: i32) -> PingResponse {
        PingResponse { status_code }
    }
}
