// Stocks Tracker API
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// The version of the OpenAPI document: 0.1.2
//
// Generated by: https://openapi-generator.tech

use serde::{
    Deserialize,
    Serialize,
};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResponse {
    #[serde(rename = "chat_id")]
    pub chat_id: i64,
    #[serde(
        rename = "first_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<Option<String>>,
    #[serde(
        rename = "second_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub second_name: Option<Option<String>>,
    #[serde(rename = "tg_id")]
    pub tg_id: i64,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    #[serde(rename = "username")]
    pub username: String,
}

impl UserResponse {
    pub fn new(chat_id: i64, tg_id: i64, user_id: i32, username: String) -> UserResponse {
        UserResponse {
            chat_id,
            first_name: None,
            second_name: None,
            tg_id,
            user_id,
            username,
        }
    }
}
