// Stocks Tracker API
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// The version of the OpenAPI document: 0.1.2
//
// Generated by: https://openapi-generator.tech

use serde::{
    Deserialize,
    Serialize,
};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionResponse {
    #[serde(rename = "version")]
    pub version: String,
}

impl VersionResponse {
    pub fn new(version: String) -> VersionResponse {
        VersionResponse { version }
    }
}
