log_level: TRACE
log_filepath: stdout
refresh_interval_sec: 5
notify_interval_sec: 5
api_cors_origins:
  - http://localhost:4400
  - http://localhost:5500
  - https://stocks-tracker.ru
  - https://cdn.stocks-tracker.ru
  - https://swagger.stocks-tracker.ru
api_server_port: 3000
moex_base_url: https://iss.moex.com
admin_static_s3_bucket: static.admin.stocks-tracker.ru
posrgres_user: postgres
postgres_password: set this var via .env
postgres_host: localhost
postgres_port: 5432
postgres_database: postgres
admin_user_login: demo@sea-ql.org
admin_user_pid: 79a6243b-088d-5d95-9b16-a2d1689e291f
admin_user_password: set this var via .env
admin_user_token: set this var via .env
redis_connection_string: set this var via .env
telegram_bot_token: set this var via .env
e2e_backend_taget_url: https://api.stress.stocks-tracker.ru
e2e_token: set this var via .env
