apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.meta.name }}-file-config
  namespace: {{ .Values.meta.namespace }}
data:
  app.yaml: |-
    {{ .Files.Get "backend/config/app.default.yaml" | indent 4 }}
