workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

stages:
  - prepare
  - build
  - test
  - deploy-testing
  - test-e2e
  - deploy-production
  - allure-report

.images:
  backend-builder: &backend-builder cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/backend-builder:latest

.job-test-template: &job-test-template
  when: on_success
  image: *backend-builder
  dependencies: []
  variables:
    TEST_TYPE: TEST_TYPE_PLACEHOLDER
    SEC: stocks-tracker-testing-secrets.yaml
    VALUES: stocks-tracker-testing-values.yaml
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/tests
  script:
    - cd backend
    - sops --decrypt ../infra/helm/values/${SEC} | yq '.secret | to_entries | .[] | "\(.key)=\"\(.value)\""' -rc > .env
    - cat ../infra/helm/values/${VALUES} | yq '.env | to_entries | .[] | "\(.key)=\"\(.value)\""' -rc >> .env
    - env
    - APP_POSTGRES_HOST="patroni-it-$CI_COMMIT_SHORT_SHA.patroni.svc" cargo nextest run --nff --no-capture --archive-file ./tests/${TEST_TYPE}.tar.zst --test-threads 1
  after_script:
    - mkdir -p ./backend/allure-results
    - mv ./backend/target/nextest/default/junit.xml ./backend/allure-results/${TEST_TYPE}.xml
  artifacts:
    when: always
    paths:
      - ./backend/allure-results/${TEST_TYPE}.xml

.aws-env: &aws-env
  AWS_DEFAULT_REGION: ru-central1
  AWS_ENDPOINT_URL: https://storage.yandexcloud.net
  S3_BUCKET: allure.stocks-tracker.ru

job-build-push-ci-images:
  stage: prepare
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies: []
  cache: []
  parallel:
    matrix:
      - DOCKERFILE:
        - backend-builder
        - reporter
        - patroni
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/infra/ci/${DOCKERFILE}.Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${DOCKERFILE}:latest"
  only:
    changes:
      - ./infra/ci/*.Dockerfile

job-lint-backend:
  stage: prepare
  image: *backend-builder
  script:
    - cd backend
    - cargo clippy --all-targets --all-features -- -D warnings

job-format-backend:
  stage: prepare
  image: *backend-builder
  script:
    - cd backend
    - cargo fmt --all -- --check

job-build-backend:
  stage: build
  image: *backend-builder
  needs:
    - job: job-build-push-ci-images
      optional: true
  dependencies: []
  variables:
    # RUSTC_WRAPPER: sccache
    # SCCACHE_DIR: .sccache-cache
    # SCCACHE_CACHE_SIZE: "10G"
    RUSTC_WRAPPER: sccache
    SCCACHE_BUCKET: stocks-tracker.ru
    SCCACHE_REGION: ru-central1
    SCCACHE_ENDPOINT: storage.yandexcloud.net
    SCCACHE_S3_KEY_PREFIX: cache/sccache
  cache:
    # - key: sccache-local
    #   policy: pull-push
    #   paths:
    #     - .sccache-cache
    - key: backend-bin
      policy: push
      paths:
        - backend/bin
    - key: backend-tests
      policy: push
      paths:
        - backend/tests
        - backend/allure-results
  before_script:
    - apt install xmlstarlet -y
    - sccache --version
    - sccache --start-server
    - cd backend
  script:
    - cargo +nightly build --release --all-targets
    - mkdir -p ./bin
    - find ./target/${CARGO_BUILD_TARGET}/release -maxdepth 1 -type f -executable | xargs -I '{}' mv {} ./bin
    - mkdir -p ./tests
    # пакуем исполняемые файлы тестов в архивы, чтобы передать их в следующие задачи
    - cargo nextest archive --release --lib --archive-file ./tests/unit.tar.zst
    - cargo nextest archive --release --test "*it*" --archive-file ./tests/integration.tar.zst
    - cargo nextest archive --release --test "*e2e*" --archive-file ./tests/e2e.tar.zst
    # тут костыль с заполнением тестов тегом skipped
    - mkdir -p ./allure-results
    - cargo nextest run --release --lib --nff --no-capture || true
    - >-
      xmlstarlet ed -L -P 
      -s '//testcase' -t elem -n skipped -v ''
      -d '//failure'
      ./target/nextest/default/junit.xml
    - mv ./target/nextest/default/junit.xml ./allure-results/unit.xml
    - cargo nextest run --release --test "*it*" --nff --no-capture || true
    - >-
      xmlstarlet ed -L -P 
      -s '//testcase' -t elem -n skipped -v ''
      -d '//failure'
      ./target/nextest/default/junit.xml
    - mv ./target/nextest/default/junit.xml ./allure-results/integration.xml
    - cargo nextest run --release --test "*e2e*" --nff --no-capture || true
    - >-
      xmlstarlet ed -L -P 
      -s '//testcase' -t elem -n skipped -v ''
      -d '//failure'
      ./target/nextest/default/junit.xml
    - mv ./target/nextest/default/junit.xml ./allure-results/e2e.xml
  after_script:
    - sccache --show-stats

job-push-backend:
  stage: build
  when: on_success
  needs:
    - job-build-backend
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies: []
  cache:
    - key: backend-bin
      policy: pull
      paths:
        - backend/bin
  parallel:
    matrix:
      - APP:
        - api
        - admin
        - notifier
        - refresher
        - migration
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --build-arg "APP=${APP}"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${APP}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${APP}:latest"

job-test-unit:
  <<: *job-test-template
  stage: test
  needs:
    - job-build-backend
  variables:
    TEST_TYPE: unit
    SEC: stocks-tracker-testing-secrets.yaml
    VALUES: stocks-tracker-testing-values.yaml


job-up-db-integration: &job-helmwave-db-integration
  stage: test
  needs:
    - job-push-backend
  when: on_success
  image: diamon/helmwave:latest
  dependencies: []
  cache: []
  variables:
    COMMAND: up
  script:
    - >-
      CI_ENVIRONMENT_NAME="${CI_COMMIT_SHORT_SHA}"
      helmwave ${COMMAND}
      --build
      --yml
      --tpl infra/helm/helmwave.db.integration.yml.tpl

job-test-integration:
  <<: *job-test-template
  stage: test
  needs:
    - job-test-unit
    - job-up-db-integration
  variables:
    TEST_TYPE: integration
    SEC: stocks-tracker-migration-it-secrets.yaml
    VALUES: stocks-tracker-migration-it-values.yaml

job-down-db-integration:
  <<: *job-helmwave-db-integration
  needs:
    - job-test-integration
  variables:
    COMMAND: down
  when: always

job-deploy-backend-testing:
  stage: deploy-testing
  needs:
    - job-push-backend
    - job-test-integration
  when: on_success
  image: diamon/helmwave:latest
  dependencies: []
  cache: []
  script:
    - >-
      CI_COMMIT_TAG="${CI_COMMIT_SHORT_SHA}"
      helmwave up
      --build
      -f infra/helm/helmwave.app.testing.yml

job-test-e2e:
  <<: *job-test-template
  stage: test-e2e
  needs:
    - job-deploy-backend-testing
  variables:
    TEST_TYPE: e2e
    SEC: stocks-tracker-testing-secrets.yaml
    VALUES: stocks-tracker-testing-values.yaml

job-deploy-backend-production:
  stage: deploy-production
  needs:
    - job-test-e2e
  when: on_success
  image: diamon/helmwave:latest
  dependencies: []
  cache: []
  script:
    - >-
      CI_COMMIT_TAG="${CI_COMMIT_SHORT_SHA}"
      helmwave up
      --build
      -f infra/helm/helmwave.app.production.yml

job-allure-report:
  stage: allure-report
  when: always
  variables:
    <<: *aws-env
  needs:
    - job-test-unit
    - job-test-integration
    - job-test-e2e
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/allure-results
  image: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/reporter:latest
  script:
    - aws s3 sync s3://${S3_BUCKET}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/latest/history ./backend/allure-results/history
    - export BUILD_ORDER=$(aws s3 ls s3://${S3_BUCKET}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/ | wc -l)
    - |
      cat <<EOF > ./backend/allure-results/environment.properties
      branch=${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
      build_number=${CI_PIPELINE_ID}
      EOF
    - |
      cat <<EOF > ./backend/allure-results/executor.json
      {
        "name": "${CI_RUNNER_ID}",
        "type": "gitlab",
        "buildUrl": "${CI_PIPELINE_URL}",
        "buildOrder": ${BUILD_ORDER},
        "buildName": "${CI_COMMIT_TITLE}",
        "reportUrl": "https://${S3_BUCKET}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/${CI_COMMIT_SHORT_SHA}"
      }
      EOF
    - ls backend/allure-results -la
    - cat ./backend/allure-results/executor.json
    - >-
      xmlstarlet ed -L -P 
      -i '/testsuites/testsuite[not(@timestamp)]'
      -t attr -n timestamp
      -v "$(xmlstarlet sel -t -v '/testsuites/@timestamp' ./backend/allure-results/unit.xml)"
      ./backend/allure-results/unit.xml
    - >-
      xmlstarlet ed -L -P 
      -i '/testsuites/testsuite[not(@timestamp)]'
      -t attr -n timestamp
      -v "$(xmlstarlet sel -t -v '/testsuites/@timestamp' ./backend/allure-results/integration.xml)"
      ./backend/allure-results/integration.xml
    - >-
      xmlstarlet ed -L -P 
      -i '/testsuites/testsuite[not(@timestamp)]'
      -t attr -n timestamp
      -v "$(xmlstarlet sel -t -v '/testsuites/@timestamp' ./backend/allure-results/e2e.xml)"
      ./backend/allure-results/e2e.xml
    - allure --version
    - allure --verbose generate -c ./backend/allure-results -o ./backend/allure-report
    - >-
      aws s3 sync 
      ./backend/allure-report
      s3://${S3_BUCKET}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/latest
    - >-
      aws s3 sync 
      ./backend/allure-report
      s3://${S3_BUCKET}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/${CI_COMMIT_SHORT_SHA}
    - cat ./backend/allure-report/widgets/executors.json
    - echo "https://${S3_BUCKET}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/latest"
    - 'curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes?body=hello"'

  artifacts:
    paths:
      - ./backend/allure-report
    reports:
      junit: ./backend/allure-results/*.xml

job-build-frontend:
  stage: build
  when: on_success
  variables:
    API: https://api.stocks-tracker.ru
    ENVIRONMENT_NAME: "testing"
  environment: $ENVIRONMENT_NAME
  image: node:23.11.0-slim
  dependencies: []
  cache: []
  before_script:
    - cd frontend
    - yarn
  script:
    - yarn nx build app
  artifacts:
    paths:
      - frontend/dist/apps/app/
    when: always
  only:
    changes:
      - frontend
      - docs

job-deploy-frontend:
  stage: deploy-testing
  when: on_success
  needs:
    - job-build-frontend
    - job-test-integration
  variables:
    <<: *aws-env
  dependencies: []
  cache: []
  image:
    name: amazon/aws-cli:2.27.4
    entrypoint: ["/usr/bin/env"]
  script:
    - >-
      aws s3 sync ./frontend/dist/apps/app ${S3_BUCKET}
  only:
    changes:
      - frontend
      - docs
