workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

stages:
  - prepare
  - build
  - test
  - deploy-testing
  - test-e2e
  - allure-report
  - deploy-production

.aws-env: &aws-env
  AWS_DEFAULT_REGION: ru-central1
  AWS_ENDPOINT_URL: https://storage.yandexcloud.net
  S3_BUCKET: allure.stocks-tracker.ru

job-build-push-ci-images:
  stage: prepare
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies: []
  cache: []
  parallel:
    matrix:
      - DOCKERFILE:
        - builder
        - reporter
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/infra/ci/$DOCKERFILE.Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/$DOCKERFILE:latest"
  only:
    changes:
      - ./infra/ci/*.Dockerfile

job-build-backend:
  stage: build
  image: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/backend-builder:latest
  needs:
    - job: job-build-push-ci-images
      optional: true
  dependencies: []
  variables:
    # RUSTC_WRAPPER: sccache
    # SCCACHE_DIR: .sccache-cache
    # SCCACHE_CACHE_SIZE: "10G"
    RUSTC_WRAPPER: sccache
    SCCACHE_BUCKET: stocks-tracker.ru
    SCCACHE_REGION: ru-central1
    SCCACHE_ENDPOINT: storage.yandexcloud.net
    SCCACHE_S3_KEY_PREFIX: cache/sccache
  cache:
    # - key: sccache-local
    #   policy: pull-push
    #   paths:
    #     - .sccache-cache
    - key: backend-bin
      policy: push
      paths:
        - backend/bin
    - key: backend-tests
      policy: push
      paths:
        - backend/tests
  before_script:
    - sccache --version
    - sccache --start-server
    - cd backend
  script:
    - cargo +nightly build --release --all-targets
    - mkdir ./bin
    - find ./target/$CARGO_BUILD_TARGET/release -maxdepth 1 -type f -executable | xargs -I '{}' mv {} ./bin
    - mkdir ./tests
    - cargo nextest archive --release --lib --archive-file ./tests/unit.tar.zst
    - cargo nextest archive --release --test "*it*" --archive-file ./tests/integration.tar.zst
    - cargo nextest archive --release --test "*e2e*" --archive-file ./tests/e2e.tar.zst
  after_script:
    - sccache --show-stats

job-test-unit:
  stage: test
  when: on_success
  image: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/backend-builder:latest
  dependencies: []
  needs:
    - job-build-backend
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/tests
  script:
    - cd backend
    - cargo nextest run --archive-file ./tests/unit.tar.zst
    - mkdir allure-results
    - mv ./target/nextest/default/junit.xml ./allure-results/unit.xml
  artifacts:
    paths:
      - ./backend/allure-results/unit.xml
    reports:
      junit: ./backend/allure-results/unit.xml

job-test-integration:
  stage: test
  when: on_success
  needs:
    - job-test-unit
  image: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/backend-builder:latest
  dependencies: []
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/tests
  script:
    - cd backend
    - sops --decrypt ./config/app.secrets.production.yaml | yq '.secret | to_entries | .[] | "\(.key)=\"\(.value)\""' -rc > .env
    - source .env
    - cargo nextest run --archive-file ./tests/integration.tar.zst --test-threads 1
    - mkdir allure-results
    - mv ./target/nextest/default/junit.xml ./allure-results/integration.xml
  artifacts:
    paths:
      - ./backend/allure-results/integration.xml
    reports:
      junit: ./backend/allure-results/integration.xml

job-push-backend:
  stage: build
  when: on_success
  needs:
    - job-build-backend
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies: []
  cache:
    - key: backend-bin
      policy: pull
      paths:
        - backend/bin
  parallel:
    matrix:
      - APP:
        - api
        - admin
        - notifier
        - refresher
        - migration
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --build-arg "APP=${APP}"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${APP}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${APP}:latest"

job-deploy-backend-testing:
  stage: deploy-testing
  needs:
    - job-push-backend
    - job-test-integration
  when: on_success
  variables:
    ENVIRONMENT_NAME: "testing"
  environment: $ENVIRONMENT_NAME
  image: alpine/k8s:1.30.12
  dependencies: []
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/tests
  before_script:
    - helm plugin install https://github.com/jkroepke/helm-secrets --version v4.6.0
    - apk add sops
  script:
    - kubectl config use-context ${CI_PROJECT_PATH}:yandex-cloud-k3s
    - HELM_NAME="stocks-tracker-${CI_ENVIRONMENT_NAME}"
    - >-
      helm secrets
      -n stocks-tracker
      upgrade ${HELM_NAME}-release ./infra/charts/stocks-tracker
      --install
      --atomic
      --set "meta.name=${HELM_NAME}"
      --set "image.tag=${CI_COMMIT_SHORT_SHA}"
      -f backend/config/app.secrets.production.yaml

job-test-e2e:
  stage: test-e2e
  when: on_success
  needs:
    - job-deploy-backend-testing
  image: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/backend-builder:latest
  dependencies: []
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/tests
  script:
    - cd backend
    - sops --decrypt ./config/app.secrets.production.yaml | yq '.secret | to_entries | .[] | "\(.key)=\"\(.value)\""' -rc > .env
    - source .env
    - cargo nextest run --archive-file ./tests/e2e.tar.zst --test-threads 1
    - mkdir allure-results
    - mv ./target/nextest/default/junit.xml ./allure-results/e2e.xml
  artifacts:
    paths:
      - ./backend/allure-results/e2e.xml
    reports:
      junit: ./backend/allure-results/e2e.xml

job-allure-report:
  stage: allure-report
  when: always
  variables:
    <<: *aws-env
  needs:
    - job-test-unit
    - job-test-integration
    - job-test-e2e
  cache: []
  image: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/reporter:latest
  script:
    - aws s3 sync s3://$S3_BUCKET/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME/history ./backend/allure-results/history
    - allure generate -c ./backend/allure-results -o ./backend/allure-report
    - aws s3 sync ./backend/allure-report s3://$S3_BUCKET/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - echo "https://$S3_BUCKET/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
  artifacts:
    paths:
      - ./backend/allure-report

job-build-frontend:
  stage: build
  when: on_success
  variables:
    API: https://api.stocks-tracker.ru
    ENVIRONMENT_NAME: "testing"
  environment: $ENVIRONMENT_NAME
  image: node:23.11.0-slim
  dependencies: []
  cache: []
  before_script:
    - cd frontend
    - yarn
  script:
    - yarn nx build app
  artifacts:
    paths:
      - frontend/dist/apps/app/
    when: always
  only:
    changes:
      - frontend
      - docs

job-deploy-frontend:
  stage: deploy-testing
  when: on_success
  needs:
    - job-build-frontend
    - job-test-integration
  variables:
    <<: *aws-env
  dependencies: []
  cache: []
  image:
    name: amazon/aws-cli:2.27.4
    entrypoint: ["/usr/bin/env"]
  script:
    - >-
      aws s3 sync ./frontend/dist/apps/app $S3_BUCKET
  only:
    changes:
      - frontend
      - docs

# job-deploy-backend-production:
#   stage: deploy-production
#   needs:
#     - job-push-backend
#   when: on_success
#   variables:
#     ENVIRONMENT_NAME: "production"
#   environment: $ENVIRONMENT_NAME
#   image: alpine/k8s:1.30.12
#   script:
#     - kubectl config use-context ${CI_PROJECT_PATH}:yandex-cloud-k3s
#     - HELM_NAME="stocks-tracker-${CI_ENVIRONMENT_NAME}"
#     - >-
#       helm
#       -n stocks-tracker
#       upgrade ${HELM_NAME}-release ./infra/charts/stocks-tracker
#       --install
#       --atomic
#       --set "meta.name=${HELM_NAME}"
#       --set "image.tag=${CI_COMMIT_SHORT_SHA}"
#       --set "secret.APP_POSTGRES_CONNECTION_STRING=${APP_POSTGRES_CONNECTION_STRING}"
#       --set "secret.APP_REDIS_CONNECTION_STRING=${APP_REDIS_CONNECTION_STRING}"
#       --set "secret.APP_TELEGRAM_BOT_TOKEN=${APP_TELEGRAM_BOT_TOKEN}"
