workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

stages:
  - prepare
  - checks
  - build
  - test-unit
  - deploy-stress
  - test-integration
  - test-e2e
  - deploy-testing
  - deploy-production
  - allure-report

.images:
  backend-builder: &backend-builder cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/backend-builder:latest

.job-test-backend: &job-test-backend
  when: on_success
  image: *backend-builder
  dependencies: []
  variables:
    TEST_TYPE: TEST_TYPE_PLACEHOLDER
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/tests
  script:
    - export VALUES='../infra/helm/values/stocks-tracker-stress-values.yaml'
    - export SEC=.'./infra/helm/values/stocks-tracker-stress-secrets.yaml'
    - cd backend
    - sops --decrypt ${SEC} | yq '.secret | to_entries | .[] | "\(.key)=\"\(.value)\""' -rc > .env
    - cat ${VALUES} | yq '.env | to_entries | .[] | "\(.key)=\"\(.value)\""' -rc >> .env
    - cargo nextest run --nff --no-capture --archive-file ./tests/${TEST_TYPE}.tar.zst --test-threads 1
  after_script:
    - mkdir -p ./backend/allure-results
    - mv ./backend/target/nextest/default/junit.xml ./backend/allure-results/${TEST_TYPE}.xml
  artifacts:
    when: always
    paths:
      - ./backend/allure-results/${TEST_TYPE}.xml

.job-deploy-backend: &job-deploy-backend
  stage: deploy-testing
  needs:
    - job-push-backend
    - job-test-integration
  when: on_success
  image: diamon/helmwave:latest
  variables:
    STAGE: STAGE_PLACEHOLDER
  dependencies: []
  cache: []
  script:
    - >-
      helmwave up
      --build
      --yml
      --tpl infra/helm/helmwave.app.yml.tpl

.aws-env: &aws-env
  AWS_DEFAULT_REGION: ru-central1
  AWS_ENDPOINT_URL: https://storage.yandexcloud.net
  S3_BUCKET: allure.stocks-tracker.ru

job-build-push-ci-images:
  stage: prepare
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies: []
  cache: []
  parallel:
    matrix:
      - DOCKERFILE:
        - backend-builder
        - reporter
        - patroni
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/infra/ci/${DOCKERFILE}.Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${DOCKERFILE}:latest"
  only:
    changes:
      - ./infra/ci/*.Dockerfile

# job-lint-backend:
#   stage: checks
#   image: *backend-builder
#   script:
#     - cd backend
#     - cargo clippy --all-targets --all-features -- -D warnings

job-format-backend:
  stage: checks
  image: *backend-builder
  script:
    - cd backend
    - cargo fmt --all -- --check

job-complexity-backend:
  stage: checks
  image: *backend-builder
  script:
    - ./infra/ci/scripts/job-complexity-backend.sh

job-build-backend:
  stage: build
  image: *backend-builder
  needs:
    - job: job-build-push-ci-images
      optional: true
  dependencies: []
  variables:
    # RUSTC_WRAPPER: sccache
    # SCCACHE_DIR: .sccache-cache
    # SCCACHE_CACHE_SIZE: "10G"
    RUSTC_WRAPPER: sccache
    SCCACHE_BUCKET: stocks-tracker.ru
    SCCACHE_REGION: ru-central1
    SCCACHE_ENDPOINT: storage.yandexcloud.net
    SCCACHE_S3_KEY_PREFIX: cache/sccache
  cache:
    # - key: sccache-local
    #   policy: pull-push
    #   paths:
    #     - .sccache-cache
    - key: backend-bin
      policy: push
      paths:
        - backend/bin
    - key: backend-tests
      policy: push
      paths:
        - backend/tests
        - backend/allure-results
  script:
    - ./infra/ci/scripts/job-build-backend.sh
  after_script:
    - sccache --show-stats

job-push-backend:
  stage: build
  when: on_success
  needs:
    - job-build-backend
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies: []
  cache:
    - key: backend-bin
      policy: pull
      paths:
        - backend/bin
  parallel:
    matrix:
      - APP:
        - api
        - admin
        - notifier
        - refresher
        - migration
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --build-arg "APP=${APP}"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${APP}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/${APP}:latest"

job-test-unit:
  <<: *job-test-backend
  stage: test-unit
  needs:
    - job-build-backend
  variables:
    TEST_TYPE: unit

job-deploy-backend-stress:
  <<: *job-deploy-backend
  stage: deploy-stress
  needs:
    - job-push-backend
  variables:
    STAGE: stress

job-test-integration:
  <<: *job-test-backend
  stage: test-integration
  needs:
    - job-deploy-backend-stress
    - job-test-unit
  variables:
    TEST_TYPE: integration

job-test-e2e:
  <<: *job-test-backend
  stage: test-e2e
  needs:
    - job-test-integration
  variables:
    TEST_TYPE: e2e

job-deploy-backend-testing:
  <<: *job-deploy-backend
  stage: deploy-testing
  needs:
    - job-test-e2e
  variables:
    STAGE: testing

job-deploy-backend-production:
  <<: *job-deploy-backend
  stage: deploy-production
  needs:
    - job-test-e2e
  variables:
    STAGE: production

job-allure-report:
  stage: allure-report
  when: always
  variables:
    <<: *aws-env
  needs:
    - job-test-unit
    - job-test-integration
    - job-test-e2e
  cache:
    - key: backend-tests
      policy: pull
      paths:
        - backend/allure-results
  image: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/reporter:latest
  script:
    - ./infra/ci/scripts/job-allure-report.sh
  artifacts:
    paths:
      - ./backend/allure-report
    reports:
      junit: ./backend/allure-results/*.xml

