//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod actives;
pub mod notifications;
pub mod sent;
pub mod users;

seaography::register_entity_modules!([actives, notifications, sent, users,]);
