//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{
    Deserialize,
    Serialize,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub notification_id: i32,
    pub portfolio_id: i32,
    pub active_id: i32,
    #[sea_orm(column_type = "Double")]
    pub limit_upper: f64,
    #[sea_orm(column_type = "Double")]
    pub limit_lower: f64,
    pub limit_type: String,
    pub resend_interval_sec: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::actives::Entity",
        from = "Column::ActiveId",
        to = "super::actives::Column::ActiveId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Actives,
    #[sea_orm(has_one = "super::sent::Entity")]
    Sent,
}

impl Related<super::actives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Actives.def()
    }
}

impl Related<super::sent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
