//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::{
    actives::Entity as Actives,
    notifications::Entity as Notifications,
    sent::Entity as Sent,
    users::Entity as Users,
};
