//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{
    Deserialize,
    Serialize,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub user_id: i32,
    #[sea_orm(unique)]
    pub tg_id: i64,
    #[sea_orm(unique)]
    pub chat_id: i64,
    #[sea_orm(unique)]
    pub username: String,
    pub first_name: Option<String>,
    pub second_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::actives::Entity")]
    Actives,
}

impl Related<super::actives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Actives.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
