[package]
name = "admin"
version.workspace = true
edition.workspace = true

[dependencies]
adapters = { path = "../../libs/adapters" }

# Web and networking
axum = { workspace = true, features = ["tokio", "http1", "tracing"] }
async-graphql-axum = { workspace = true }
sea-orm-pro = { workspace = true }
http = { workspace = true }
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "mock",
] }
seaography = { workspace = true, features = [
    "with-decimal",
    "with-chrono",
    "with-uuid",
    "field-snake-case",
] }
axum-static-s3 = { workspace = true }
aws-config = { workspace = true, features = ["behavior-version-latest"] }

# Async and runtime
tokio = { workspace = true, features = ["full"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
secrecy = { workspace = true }
anyhow = { workspace = true }
