meta:
  name: stocks-tracker-testing
  namespace: stocks-tracker

image:
  repository: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker
  tag: latest
  command: ["./app"]

ingress:
  host: api.stocks-tracker.ru
  path: /
  tls:
    enabled: false
    redirectHttp: false
    # secretName: custom-tls-cert # Optional: specify if you have a pre-created TLS secret
  timeouts:
    request: 30s
  rateLimit:
    enabled: false
    average: 100
    burst: 50
  admin:
    host: admin.stocks-tracker.ru
    path: /
    tls:
      enabled: false
      redirectHttp: false



port: 3000

scaling:
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 70

rollingUpdate:
  maxUnavailable: 5
  maxSurge: 5

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

# Add these sections to your existing values.yaml
redis:
  replicas: 1
  image:
    repository: redis
    tag: 7.0-alpine
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  storage:
    size: 1Gi
  # Uncomment and set a password if needed
  # password: your-redis-password

postgres:
  image:
    repository: postgres
    tag: 14-alpine
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  storage:
    size: 5Gi
  database: stocks_tracker
  username: postgres
  password: change-me-in-production


env:
  REDIS_HOST: "stocks-tracker-testing-redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "stocks-tracker-testing-postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "stocks_tracker"
  POSTGRES_USER: "postgres"

secret:
  REDIS_PASSWORD: "your-redis-password"
  POSTGRES_PASSWORD: "change-me-in-production"
  APP_REDIS_CONNECTION_STRING: "redis://your-redis-password@stocks-tracker-testing-redis-service:6379/0"
  APP_POSTGRES_CONNECTION_STRING: "postgresql://postgres:change-me-in-production@stocks-tracker-testing-postgres-service:5432/stocks_tracker"
  DATABASE_URL: "postgresql://postgres:change-me-in-production@stocks-tracker-testing-postgres-service:5432/stocks_tracker"
