[package]
name = "adapters"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
# stocks_tracker libs
domain = { path = "../domain" }

# Async and runtime
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }

# Web and networking
reqwest = { workspace = true, default-features = false, features = [
    "json",
    "rustls-tls",
] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_derive = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }

# Database
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "mock",
] }
seaography = { workspace = true, features = [
    "with-decimal",
    "with-chrono",
    "with-uuid",
    "field-snake-case",
] }
redis = { workspace = true, features = ["tokio-comp"] }
chrono = { workspace = true }
dotenvy = { workspace = true }
shaku = { workspace = true }
secrecy = { workspace = true, features = ["serde"] }

# Logging and tracing
log = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { workspace = true, features = ["json", "env-filter"] }
# tracing-opentelemetry = { workspace = true }
# opentelemetry-otlp = { workspace = true }


# Telegram
teloxide = { workspace = true, default-features = false, features = [
    "macros",
    "rustls",
] }
config = { workspace = true }
