[package]
name = "adapters"
version = "0.1.0"
edition = "2024"

[features]
default = ["fake", "mockall"]
production = []
fake = ["dep:fake"]

[dependencies]
# stocks_tracker libs
domain = { path = "../domain" }

# Async and runtime
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1.88"

# Web and networking
reqwest = { workspace = true, default-features = false, features = [
    "json",
    "rustls-tls",
] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_derive = "1.0"
quick-xml = { workspace = true, features = ["serialize"] }

# Database
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "mock",
] }
seaography = { workspace = true, features = [
    "with-decimal",
    "with-chrono",
    "with-uuid",
    "field-snake-case",
] }
redis = { workspace = true, features = ["tokio-comp"] }

# Utilities
uuid = { workspace = true, features = ["v4"] }
chrono = "0.4"
dotenvy = "0.15.7"
shaku = "0.6.2"

# Logging and tracing
log = "0.4.26"
tracing = { workspace = true, features = ["attributes"] }
tracing-subscriber = { workspace = true, features = ["json"] }
tracing-appender = "0.2.3"

# Telegram
teloxide = { workspace = true, default-features = false, features = [
    "macros",
    "rustls",
] }

# Testing and mocking
mockall = { workspace = true, optional = true }
fake = { workspace = true, features = ["chrono", "derive"], optional = true }
config = "0.15.11"
