apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.meta.name }}-api-deployment
  namespace: {{ .Values.meta.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.meta.name }}-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  template:
    metadata:
      namespace: {{ .Values.meta.namespace }}
      labels:
        app: {{ .Values.meta.name }}-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gitlab-runner
                    operator: In
                    values:
                      - "true"
      containers:
        - name: {{ .Values.meta.name }}-api
          image: "{{ .Values.image.repository }}/apps:{{ .Values.image.tag }}"
          command: ["./api"]
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /api/v1/health/ping
              port: {{ .Values.port }}
              httpHeaders:
                - name: Host
                  value: {{ .Values.ingress.api.host }}
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ .Values.meta.name }}-config
            - secretRef:
                name: {{ .Values.meta.name }}-secret
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
