apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.name }}-api-node-port
  namespace: {{ .Values.meta.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.meta.name }}-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.app.node_port }}
