{{- if .Values.features.postgres }}
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ .Values.meta.name }}-migration-job-{{ .Values.image.tag }}'
  namespace: {{ .Values.meta.namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Values.meta.name }}-migration
          image: "{{ .Values.image.repository }}/apps:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              export APP_POSTGRES_CONNECTION_STRING="postgres://${APP_POSTGRES_USER}:${APP_POSTGRES_PASSWORD}@${APP_POSTGRES_HOST}:${APP_POSTGRES_PORT}/${APP_POSTGRES_DATABASE}"; 
              echo $APP_POSTGRES_CONNECTION_STRING
              /app/migration up --database-url $APP_POSTGRES_CONNECTION_STRING
          envFrom:
            - configMapRef:
                name: {{ .Values.meta.name }}-config
            - secretRef:
                name: {{ .Values.meta.name }}-secret
{{- end }}