{{- if .Values.features.mongodb }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.meta.name }}-mongodb
  namespace: {{ .Values.meta.namespace }}
spec:
  serviceName: {{ .Values.meta.name }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.meta.name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Values.meta.name }}-mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
              name: mongo
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            limits:
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
              memory: {{ .Values.mongodb.resources.limits.memory }}
            requests:
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
              memory: {{ .Values.mongodb.resources.requests.memory }}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mongodb.storage.size }}
{{- end }}


