project: stocks-tracker-testing
version: 0.42.2

.options: &options
  create_namespace: true
  wait: true
  timeout: 1m
  max_history: 3
  atomic: true
  context: the-qsb/stocks-tracker:main

releases:

  - name: patroni-testing
    namespace: patroni
    <<: *options
    chart: ./infra/helm/charts/patroni
    values:
      - ./infra/helm/values/stocks-tracker-testing-values.yaml
      - src: ./infra/helm/values/stocks-tracker-testing-secrets.yaml
        renderer: sops
      - ./infra/helm/values/patroni-testing-values.yaml

  - name: stocks-tracker-testing-env
    namespace: stocks-tracker
    <<: *options
    chart: ./infra/helm/charts/stocks-tracker-env
    values:
      - ./infra/helm/values/stocks-tracker-testing-values.yaml
      - src: ./infra/helm/values/stocks-tracker-testing-secrets.yaml
        renderer: sops

  - name: stocks-tracker-testing-migration
    namespace: stocks-tracker
    <<: *options
    chart: ./infra/helm/charts/stocks-tracker-migration
    depends_on:
      - stocks-tracker-testing-env@stocks-tracker
      - patroni-testing@patroni
    values:
      - ./infra/helm/values/stocks-tracker-testing-values.yaml
      - src: ./infra/helm/values/stocks-tracker-testing-secrets.yaml
        renderer: sops

  - name: stocks-tracker-testing-app
    namespace: stocks-tracker
    <<: *options
    chart: ./infra/helm/charts/stocks-tracker-app
    depends_on:
      - stocks-tracker-testing-migration@stocks-tracker
    values:
      - ./infra/helm/values/stocks-tracker-testing-values.yaml
      - src: ./infra/helm/values/stocks-tracker-testing-secrets.yaml
        renderer: sops
