// Stocks Tracker API
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// The version of the OpenAPI document: 0.1.0
//
// Generated by: https://openapi-generator.tech

use serde::{
    Deserialize,
    Serialize,
};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginResponse {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "expires_in")]
    pub expires_in: i64,
    #[serde(rename = "token_type")]
    pub token_type: String,
}

impl LoginResponse {
    pub fn new(access_token: String, expires_in: i64, token_type: String) -> LoginResponse {
        LoginResponse {
            access_token,
            expires_in,
            token_type,
        }
    }
}
