// Stocks Tracker API
//
// No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
//
// The version of the OpenAPI document: 0.1.0
//
// Generated by: https://openapi-generator.tech

use serde::{
    Deserialize,
    Serialize,
};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationResponse {
    #[serde(rename = "active_id")]
    pub active_id: i32,
    #[serde(rename = "limit_lower")]
    pub limit_lower: f64,
    #[serde(rename = "limit_type")]
    pub limit_type: String,
    #[serde(rename = "limit_upper")]
    pub limit_upper: f64,
    #[serde(rename = "notification_id")]
    pub notification_id: i32,
    #[serde(rename = "portfolio_id")]
    pub portfolio_id: i32,
    #[serde(rename = "resend_interval_sec")]
    pub resend_interval_sec: i32,
}

impl NotificationResponse {
    pub fn new(
        active_id: i32,
        limit_lower: f64,
        limit_type: String,
        limit_upper: f64,
        notification_id: i32,
        portfolio_id: i32,
        resend_interval_sec: i32,
    ) -> NotificationResponse {
        NotificationResponse {
            active_id,
            limit_lower,
            limit_type,
            limit_upper,
            notification_id,
            portfolio_id,
            resend_interval_sec,
        }
    }
}
