apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.meta.name }}-patroni
  labels:
    application: {{ .Values.meta.name }}-patroni
    cluster-name: {{ .Values.meta.name }}-patroni
  annotations:
    helmwave.app/skip-diff: "true"
type: Opaque
data:
  superuser-password:
    {{ .Values.secret.APP_POSTGRES_PASSWORD | b64enc | quote }}
  replication-password:
    {{ .Values.secret.APP_POSTGRES_PASSWORD_REPLICATION | b64enc | quote }}
