apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.name }}-patroni
  labels:
    application: {{ .Values.meta.name }}-patroni
    cluster-name: {{ .Values.meta.name }}-patroni
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
