[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
# stocks_tracker libs
domain = { path = "../../libs/domain" }
adapters = { path = "../../libs/adapters" }

# Async and runtime
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
shaku = { workspace = true }
