[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[features]
default = ["fake", "mockall"]
production = []
fake = ["dep:fake"]

[dependencies]
# Async and runtime
tokio = { version = "1.29.1", features = ["full"] }
async-trait = "0.1.88"

# Utilities
chrono = "0.4"
regex = "1.11"

# Error handling
thiserror = "2.0"

# Logging and tracing
tracing = { version = "0.1", features = ["attributes"] }

# Testing and mocking (required in main code for interfaces)
mockall = { version = "0.13.1", optional = true }
fake = { version = "4.3", features = ["chrono", "derive"], optional = true }
shaku = "0.6.2"
