meta:
  name: stocks-tracker-testing
  namespace: stocks-tracker

secret:
  APP_REDIS_CONNECTION_STRING: "redis://default-redis-password@stocks-tracker-testing-redis-service:6379/0"
  APP_POSTGRES_CONNECTION_STRING: "postgresql://postgres:default-postgres-password@stocks-tracker-testing-postgres-service:5432/stocks_tracker"
