[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
# stocks_tracker libs
domain = { path = "../../libs/domain" }
adapters = { path = "../../libs/adapters" }

# Web and networking
axum = { workspace = true, features = ["tokio", "http1", "tracing"] }
axum-macros = { workspace = true }
tower-http = { workspace = true, features = [
    "cors",
    "normalize-path",
    "request-id",
    "trace",
] }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
tower-layer = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-axum = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }

# Async and runtime
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Utilities
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true }
dotenvy = { workspace = true }
shaku = { workspace = true }
secrecy = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Logging and tracing
log = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }

# Telegram
telegram-authorizer = { workspace = true }

# Testing and mocking (required in main code for interfaces)
mockall = { workspace = true, optional = true }
fake = { workspace = true, features = ["chrono", "derive"], optional = true }
jsonwebtoken = { workspace = true }
