[package]
name = "refresher"
version.workspace = true
edition.workspace = true

[dependencies]
# stocks_tracker libs
domain = { path = "../../libs/domain" }
adapters = { path = "../../libs/adapters" }

# other
tokio = { workspace = true, features = ["full"] }
shaku = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
