apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.meta.name }}-vault-ingress
  namespace: vault
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.ingress.vault.host }}
    secretName: {{ .Values.meta.name }}-vault-tls-cert
  rules:
    - host: {{ .Values.ingress.vault.host }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.ingress.vault.path }}
            backend:
              service:
                name: vault
                port:
                  number: 8200
