meta:
  name: patroni
  namespace: patroni

patroni:
  image:
    repository: cr.yandex/crpav8o4hj057l1dbgqa/the-qsb/stocks-tracker/patroni
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 3
  storage:
    size: 1Gi

env:
    APP_POSTGRES_USER: postgres
    APP_POSTGRES_PORT: '5432'
    APP_POSTGRES_DATABASE: postgres

secret:
    APP_POSTGRES_PASSWORD: zalandodemo
    APP_POSTGRES_PASSWORD_REPLICATION: rep-pass
