apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.meta.name }}-gw-config
  namespace: {{ .Values.meta.namespace }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        gzip on;
        gzip_disable "msie6";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

        location /reserved/ {
            alias /usr/share/nginx/html/;
            index index.html index.htm;
            add_header Content-Type text/html;
        }

        location / {
            alias /usr/share/nginx/html/;
            index index.html index.htm;
            add_header Content-Type text/html;
            add_header Cache-Control "public, max-age=86400, immutable";
        }

        location /management/ {
            alias /usr/share/nginx/html/;
            index management.html management.htm;
            add_header Content-Type text/html;
        }

        location /legacy/ {
            proxy_pass https://stocks-tracker.ru/;
            proxy_set_header Host stocks-tracker.ru;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /image.png {
            alias /usr/share/nginx/html/image.png;
            add_header Content-Type image/png;
            add_header Cache-Control "public, max-age=604800, immutable";
        }

        location /test.txt {
            alias /usr/share/nginx/html/test.txt;
            add_header Content-Type text/plain;
            add_header Cache-Control "public, max-age=604800, immutable";
        }

        location /status {
            alias /usr/share/nginx/html/;
            index status.html;
            add_header Cache-Control "public, max-age=604800, immutable";
        }

        location /status/nginx/ {
            stub_status;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to Stocks Tracker</title>
        <img src="image.png" alt="test image"/>
    </head>
    <body>
        <h1>Welcome to Stocks Tracker!</h1>
    </body>
    </html>
  management.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to Stocks Tracker</title>
    </head>
    <body>
        <h1>Welcome to management!</h1>
        <p>
        <a href="https://api.stocks-tracker.ru/swagger">https://api.stocks-tracker.ru/swagger</a>
        </p>
        <p>
        <a href="https://gw.stocks-tracker.ru/legacy">https://gw.stocks-tracker.ru/legacy/</a>
        </p>
        <p>
        <a href="https://stocks-tracker.ru/docs/">https://stocks-tracker.ru/docs/</a>
        </p>
        <p>
        <a href="https://stocks-tracker.ru/">https://stocks-tracker.ru/</a>
        </p>
        <p>
        <a href="https://gw.stocks-tracker.ru/">https://gw.stocks-tracker.ru/</a>
        </p>
        <p>
        <a href="https://gw.stocks-tracker.ru/reserved/">https://gw.stocks-tracker.ru/reserved/</a>
        </p>
        <p>
        <a href="https://admin.stocks-tracker.ru/admin/">https://admin.stocks-tracker.ru/admin/</a>
        </p>
        <p>
        <a href="https://gw.stocks-tracker.ru/status/nginx/">https://gw.stocks-tracker.ru/status/nginx/</a>
        </p>
        <p>
        <a href="https://gw.stocks-tracker.ru/management/">https://gw.stocks-tracker.ru/management/</a>
        </p>
    </body>
    </html>
  image.png: |
    iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAALElEQVQImWNgYGBgYGBgwAAjAwMDwz7A1goGBkYGBgYKAAACDAAABMPOAmEAAAAASUVORK5CYII=
  test.txt: |
    This is a long line for test.
    This is a long line for test.
    This is a long line for test.
    This is a long line for test.
  status.html: |
    <!DOCTYPE html>
        <html lang="ru">
        <head>
        <meta charset="UTF-8">
        <title>Status: OK</title>
        <style>
            body {
            background: #181c1f;
            color: #fff;
            font-family: sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            }
            .ok-circle {
            width: 60px;
            height: 60px;
            background: #3cb371;
            border-radius: 50%;
            margin-bottom: 20px;
            animation: pulse 1.2s infinite;
            box-shadow: 0 0 0 0 #3cb37166;
            }
            @keyframes pulse {
            0% {
                transform: scale(1);
                box-shadow: 0 0 0 0 #3cb37166;
            }
            70% {
                transform: scale(1.1);
                box-shadow: 0 0 0 18px #3cb37111;
            }
            100% {
                transform: scale(1);
                box-shadow: 0 0 0 0 #3cb37100;
            }
            }
            h1 {
            font-size: 2rem;
            margin: 0;
            letter-spacing: 1px;
            }
            .code {
            background: #222;
            color: #8f8;
            border-radius: 4px;
            padding: 2px 10px;
            margin-left: 8px;
            font-family: monospace;
            font-size: 1.1rem;
            }
        </style>
        </head>
        <body>
            <div class="ok-circle"></div>
            <h1>Status: <span class="code">200 OK</span></h1>
        </body>
        </html>
