apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.meta.name }}-replace-mirror-path
  namespace: {{ .Values.meta.namespace }}
spec:
  replacePathRegex:
    regex: "^{{ .Values.ingress.api.mirror_path }}(.*)"
    replacement: "{{ .Values.ingress.api.path }}$1"
