runnerRegistrationToken: ENC[AES256_GCM,data:q7rMaX2lYud4GvDee3aXPrUKljNHG4MfkVs7HN+Tkk5b3VaizMPDWQ0ZcVWZticxjkvuG4YL+qQ5XyzWgw==,iv:YknjXJBv33rUq6ZzeJJMsJoSPkPzc0CC40l6hLZ4+mM=,tag:Mh90FMwBMC+TddFInXDcSw==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZWdmM3psTGxQVThsTks2
            QWplaWdia3BlZ0VqTGlYd1NQRW85RTNKU1NZCkZOOEtNT3IyWVVoOXdJNE0wN3lP
            WEh3RnFxY212bXdRLzgwL0ZteCtXMmcKLS0tIFMrVTg4VWFyQm93SzlnVDNhaUls
            ZlJ3TzNNbVpyM3ZTYWRvdG9CR3pPYUkK+XbUBUPH4zx1E9wFoAM8YhhopkchBUSa
            SiGCdFVy1kVREHy2CBh0UwRKjK7sDjERutY4Ukw86BxAu744bSBR2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T10:54:33Z"
    mac: ENC[AES256_GCM,data:Wy8Jm3JL7A+MZz3Vl8pfu5HIeGLQCb1ZvaBLOdNLo6LK15hg0L/hIBm7vWAPA2RITnXLzV8neYYgvc6MxAIwCJZkvCUvnQBwISOdOZNMmGkY17+dKvF0p1PbrBKaEQVjGoUZr860L+GPNVAxclLZumWSXoi+1YYd1EiOjbZFw+Q=,iv:h7DNaBPfnhoAaOXJJXXAdWaKyK/00gqPE4lwLh0eEPQ=,tag:uZ4b/iqAowJCyFghu8G0XQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
