config:
    token: ENC[AES256_GCM,data:WNi1HqpCTJuM2vPAQ7jbCu4taO1q3lL2zmNpxtIfnYo3cIZ5elOXtoAM17yGGV7Zi6/K4Y36G1wd0H1n,iv:M8kTyqOGnL0DxhJ9c6oDephgcpFPcYoRgA+KWI6pIII=,tag:U6vh8QzhMzhEBITr3jfV2A==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMS9yYTJ6ekk5SWEwSjV2
            di8zTWxKa2o1bm1uYmZVaURINXFJV25KWWg0CnZEVmQzc3dUcEhRTkdNaEdEZHhC
            ckx4Q0kxZno2anVSTHlzOFNWWHVzZWcKLS0tIHI4bzBkL3ZyVkJuc0IrK3lrbmk0
            YWV4bHloWGdIdW1qMXcvY05mT0dQd2MKVzAKCdqErqIzR16r+S7dy13cyEbGXhOb
            wUTjNCOXeB6t/IvkfW0bhgQcY2DoKJH3IhXgBV6/CcUJxiNJkHJIjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T18:51:20Z"
    mac: ENC[AES256_GCM,data:n59oz5LN7g5zLmAfETqBlnD+SGeYpaoKdoDJvHSjVVdvOBa22wjEoZ4wd38aLrNop0nmMvw2wRK8+yIacTX3weHfOfEcgllcK+pyiKslQia7Mk8+Rel5sKAlY76DgtSMd5TIviQYNOHcKU3JGLuzBawncjgLn2U/eln+uThCvi4=,iv:SZQ26YpX5LRRVR9O6Ab8Echimfyen0fykjZsF1DRgOM=,tag:mKsg1dsS0R/284Oj8DvJmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
