grafana:
    adminUser: ENC[AES256_GCM,data:Ajh2qik=,iv:wCTqGM2jV5dIUvSZ4fjqEcPN0xzy6dPpojtsjgCteI4=,tag:SOzalFZ1ysPO+IwR06lfpg==,type:str]
    adminPassword: ENC[AES256_GCM,data:5xsZ7TXbexsGnTyolDqqBrbyWDe+S61RZ/BAHkwojKqFIGk1f4j7rw==,iv:nE8DEOBU721up8C/OdMK+tNF9nQBf8Nerwn488teE8Y=,tag:5qV3QNomY9eMu5o/UAvvbA==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUENYVmltQStQQ2NKRGFL
            bEJYa0o4dE5LbDNuRytsd2FqTnArZ2xhWnpzCk1NSFhYZWpDUmlUVGhzUGxSRUFR
            U0ZGYnd3UHh1dm1BNGN1alFsWkdMQzQKLS0tIEE2QlBqY1NaVHBoUVkyMXo3YklS
            WU43RUt4RlNMTWhjcUNJWUQxNTlIaEkKGCpFDxRV+Phm19GDlK0tyq1rbFrdu/5O
            9jOyEO2g5ORBV4VpvUsdvfzUd5mMhiJBPg3tZSYWauIrfosplDZHrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T17:45:45Z"
    mac: ENC[AES256_GCM,data:UevQhpplIYMUj7jf1bB7ZEXz5NQyDqknyK1Xbc5fMTncXuEN7P/fIrcANJtnQsSa/z3YwnYJ+y4tI710Jw3ne+tHu9O+t8uN1Qv+TPjhMp//CRJQX2etpst40uQaajHW3sxgjtqWlYCCuZVByJyijodiwuZVO13y2Ja7U+dhglk=,iv:J8AO3cQY1KKO+KZSeWEiaJBR6d4PuymEe0H76NmIBe4=,tag:hB63g9kkvPqLKg+NbhhA/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
