secret:
    APP_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:A+mlxrEthbt0HO/JdyR4/MNDn14P1xx/lzlBDyeyrBI5i+77cpH9bChUP9/yLA==,iv:3aHu1dOVly1TCdfBvDKsRGsNvPxFxUYFIVQz16PuxIo=,tag:fJqj76hgJeACTa5wcsS2mw==,type:str]
    APP_POSTGRES_PASSWORD: ENC[AES256_GCM,data:822E/RcvgAVjetM=,iv:FmUmOqJ1j9T9J66jVig8BCY+b7ZiygTRR1J5qlRLlfw=,tag:Q9WJczqoCktMKu5CYZ+14w==,type:str]
    APP_REDIS_CONNECTION_STRING: ENC[AES256_GCM,data:zzrtOZkWbkI9UdtOyK0sPG24ioCKaJ3fbS+mOgxDYrXUAcSz2LyHaF4049M6M2Qpzxm1hJgZiZlPMQ09J9EmvnP9t0w+rQ==,iv:xjtGJNKThT7bk5y3x3MlwLfvVwHmFJAaofFnHHD2QdQ=,tag:lPw+Mn917PhzpDJMHX6Bmg==,type:str]
    APP_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:ykAmXydNP0oDNDU/CVjYHh9KxrnTwkacgm4eRywMa4U=,iv:sH0WIFAFbRUTaMiXja7GZibhjOp7Qu7owthGyjuFypM=,tag:ZuvVnQvGSyVMJPm7b66cHw==,type:str]
    APP_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:rwcGVX/ervA8DCqruQR5pTeMgumirDR7Y9Y4VweDSeKjKkXcfTXRNA6rrA0mP5YJuuqyF0YPBXFNsr9qB15ZGE4cpEqo93lpvnon+49kp5KOH2z8OsepK90FTSQxHBCsuaJMEObdsqU4tbC6IEzWS0QZWNW+/77JjbmoDne8P52i/L3AiEmcPgy5xKp4CMlUpdDyaxZrkm13wHeU9VkmU3GEEke/QKSl9XsahSa0b4bo5Iis/idMLMF8umpvI+ydAkRw5IGWyMCfKSXLAIUBrhRgbUi3sscdlqYJClUHb02Sri0=,iv:LIhokA4L7Gz2am38nCOAi4OTbX4uuWWkTDzAhyFdxbY=,tag:u0QS4b0TNmCDVqlLYRIEbw==,type:str]
    APP_E2E_TOKEN: ENC[AES256_GCM,data:zctXgC++Ear/BdYJFkIEG2FOzfZJx3GxrenTMn+GkRQtV5VKR0kDbGF773GkX4Q8lUXt/34NapQFgVQJV3m1jBFkaVFXY0tqHoMf005jH+uS5+ZrBT9zCVoab/9aNcptV7o0qqDCtXL6qyNY/JpHMwl+IOBHbuTAd6xEd4sBi5NLy0GFC2/VTaeiig==,iv:0E9uoaool2K8DtMCVMWqRzSSHgEmUsLocj9715y/GHQ=,tag:vK0bTwAMD3Rl5WkHfGVAlw==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN040d1UxUlkxdUJaeXN0
            N2ZRUURRYklXV0xhZGRUMVdFUXN6WmtHVnlRCnByb043SjRPdVNtMzFRaFZyVnY4
            MDBUK25qbCtvdVA2Uk5xQW1XbE9tNjQKLS0tIFBZQ2tISVRzVXduREFNMGxZOUZZ
            ZU9iaUZDdnlIM1dibHd6Q0RUdjRWemcKbJFC4rYLFnj42aJRrlxe9Vjp6CpWCQZD
            RS+TQ/1iXeNZ+MQEN9M6UyOCXmIFsh8k2o8rELupMJgWwitpQrIvxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T23:26:21Z"
    mac: ENC[AES256_GCM,data:qMVbNaQnG6zG76Zsg4PVupFw/eVkhxBfXw0czTw2+V6ybjXXn/hFtUqpqEpbtr7X3/vDY8ZkOrdTLR7Uz1T54l7DuAnsD3EroJOVty0kSSyHt32SZuUY41aPualepny2WhtmEeNRB+oXli5ojmApWWPYBlBCgdoUZjbN8bRRY1Y=,iv:N8fS9YjO3FFwl9oBF3vc1UWkkUSSNBxKMPf3GtS4NQg=,tag:cjBvYhbVpfwXKlm9vZEZBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
