secret:
    APP_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:VH0QIywP2I6n/FNqpFPIfnoLZmT0x2kDcAMPtKihM48m5kKHc6PstRhweUheSA==,iv:W7Mi6PfLV5x5zDDq6+k8algHgBtjRoA3keHmYuexOdk=,tag:2GK8+XGdCUw/I/ImJ0+3yA==,type:str]
    APP_REDIS_CONNECTION_STRING: ENC[AES256_GCM,data:5HVKH42qL1Gw7B98rWAefHQ9XN/uGt1jemRX1UI54mtrnbtEz8L7QA6T72pQx9IXvr5FFD6fxuuaGFhv4SRt1tqdD1y1NQ==,iv:rdS8D3SzEUivVZmirWjLdA79qlIzO4oAUEyuj1ZCIjY=,tag:35bdPAU2mgOmwFC+09N9qw==,type:str]
    APP_POSTGRES_PASSWORD: ENC[AES256_GCM,data:QhtWtx21vVU3Udg=,iv:Fnudzm9OC2xeBxAT0nPWGQK5r7RY+p1VJZfxOpT5bpo=,tag:eTMyoOLsaJ1wZ02uQf1dnA==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T25JbXJkbDZoQTgzbm01
            MVBYZlJ0MVE5cVVDOHdHZDhmbzZzV3puM1JBCkdyVDFmODI5TUtrTVVWdThnV0lq
            ejRnOXRPeVlCWStOaUlSVEIzU1l4aFUKLS0tIGZyYUhWTG90UllmQXFGRERNOXdG
            bmVaVFVyWllOckhVMnJpOGNxdDdRek0KrYKeYW4OYySP/GFRkn2VDdHxrkLadytr
            7+alPsCprXrWKWkgzYh1Ib1/dvIn7KjkoLrv+00iLCeIb5Shn4XIZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T13:04:00Z"
    mac: ENC[AES256_GCM,data:hXgaQ6lr1BFQLL3izOdvDR0lGWZlGXPIhah7MeITlAIANdCIlSJ+v9A4LG6+hcUFWTVQYNAMe+I3ViIbqNdBMpy3weCFK6YZySVqrk/4YTKAtf0wnLVYTWkmdZSESlXFu3VS9tz0lF7f/LCM/O6W5kpZMyst67+hbTIHQoCZ3XA=,iv:qmOUyhfQOpWmNjc67gIYRZ7FM6CqsQyyUMPkPN3Wue8=,tag:P+dgpz96/e1n3kT7deVpcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
