meta:
  name: stocks-tracker-production

image:
  tag: '{{ env "CI_COMMIT_SHORT_SHA" }}'

ingress:
  api:
    host: api.stocks-tracker.ru
  admin:
    host: admin.stocks-tracker.ru

env:
    APP_POSTGRES_USER: postgres
    APP_POSTGRES_HOST: patroni-production.patroni.svc
    APP_POSTGRES_PORT: '5432'
    APP_POSTGRES_DATABASE: postgres

