secret:
    APP_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:A+mlxrEthbt0HO/JdyR4/MNDn14P1xx/lzlBDyeyrBI5i+77cpH9bChUP9/yLA==,iv:3aHu1dOVly1TCdfBvDKsRGsNvPxFxUYFIVQz16PuxIo=,tag:fJqj76hgJeACTa5wcsS2mw==,type:str]
    APP_POSTGRES_PASSWORD: ENC[AES256_GCM,data:822E/RcvgAVjetM=,iv:FmUmOqJ1j9T9J66jVig8BCY+b7ZiygTRR1J5qlRLlfw=,tag:Q9WJczqoCktMKu5CYZ+14w==,type:str]
    APP_REDIS_CONNECTION_STRING: ENC[AES256_GCM,data:zzrtOZkWbkI9UdtOyK0sPG24ioCKaJ3fbS+mOgxDYrXUAcSz2LyHaF4049M6M2Qpzxm1hJgZiZlPMQ09J9EmvnP9t0w+rQ==,iv:xjtGJNKThT7bk5y3x3MlwLfvVwHmFJAaofFnHHD2QdQ=,tag:lPw+Mn917PhzpDJMHX6Bmg==,type:str]
    APP_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:ykAmXydNP0oDNDU/CVjYHh9KxrnTwkacgm4eRywMa4U=,iv:sH0WIFAFbRUTaMiXja7GZibhjOp7Qu7owthGyjuFypM=,tag:ZuvVnQvGSyVMJPm7b66cHw==,type:str]
    APP_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:rwcGVX/ervA8DCqruQR5pTeMgumirDR7Y9Y4VweDSeKjKkXcfTXRNA6rrA0mP5YJuuqyF0YPBXFNsr9qB15ZGE4cpEqo93lpvnon+49kp5KOH2z8OsepK90FTSQxHBCsuaJMEObdsqU4tbC6IEzWS0QZWNW+/77JjbmoDne8P52i/L3AiEmcPgy5xKp4CMlUpdDyaxZrkm13wHeU9VkmU3GEEke/QKSl9XsahSa0b4bo5Iis/idMLMF8umpvI+ydAkRw5IGWyMCfKSXLAIUBrhRgbUi3sscdlqYJClUHb02Sri0=,iv:LIhokA4L7Gz2am38nCOAi4OTbX4uuWWkTDzAhyFdxbY=,tag:u0QS4b0TNmCDVqlLYRIEbw==,type:str]
    APP_E2E_TOKEN: ENC[AES256_GCM,data:W58eMpDKz7QednIl2ReD1gWqtLsab0ypA3A0XcetrqMgONPWG/D53G+nXwGRd1Gze2H1Kv4p7elfuVdLA64bU24vDpphMKA79A+wZ56Yu782ifCZB3TIYrVdB1qlJN5Txj0uszaNnjuYHVg8sS6L0CNS+geTZkAdUHmFuGgU2ZK2vGtip0eqJWF0Uw==,iv:abby80Gkn95Ovc3NCxsxLtAzBz8yk2cnMp3uvbbVaq4=,tag:b8YDrwaXSillpsXHkkmt+A==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN040d1UxUlkxdUJaeXN0
            N2ZRUURRYklXV0xhZGRUMVdFUXN6WmtHVnlRCnByb043SjRPdVNtMzFRaFZyVnY4
            MDBUK25qbCtvdVA2Uk5xQW1XbE9tNjQKLS0tIFBZQ2tISVRzVXduREFNMGxZOUZZ
            ZU9iaUZDdnlIM1dibHd6Q0RUdjRWemcKbJFC4rYLFnj42aJRrlxe9Vjp6CpWCQZD
            RS+TQ/1iXeNZ+MQEN9M6UyOCXmIFsh8k2o8rELupMJgWwitpQrIvxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T15:42:53Z"
    mac: ENC[AES256_GCM,data:SEXKe7UUFL0uvsCgue9Kf0MSYpEld8u6/XxwqfA6OJaqzdP6uqyIHsXRj8BQfpN4bCb1yOGY3Wc7WqkM4wft6Ng+XlH5E5RttdgVz9gDS+5B/YHesLphSG4Vz/T6Z1BoEC8VMkiNieSY6UdJLZeHyNtJ2o6uPfzDc6F4uUp4XRY=,iv:I7jusayUXwl54WACsxr9h/d8Q/KhG58pXxgkzkM56Z0=,tag:P2FB4K8+R7nmeRJUJCZAnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
