secret:
    APP_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:A+mlxrEthbt0HO/JdyR4/MNDn14P1xx/lzlBDyeyrBI5i+77cpH9bChUP9/yLA==,iv:3aHu1dOVly1TCdfBvDKsRGsNvPxFxUYFIVQz16PuxIo=,tag:fJqj76hgJeACTa5wcsS2mw==,type:str]
    APP_POSTGRES_CONNECTION_STRING: ENC[AES256_GCM,data:6QQ8K6u/Xzd+3a2Hxthy8x6QeEJmsEcE1FdSgN5BwkruPt7Ula+KKXpkx9arKVkWqPz8/KJD7XwK9uXX5/x9eUHOCbgr9WvmWKfGkEgg,iv:wxnbkDyxSqphgFeYdPNCg5yeHcpIY8zQrKQAhbH0Abc=,tag:Heac9TEnwU7Uswmn/Kztiw==,type:str]
    APP_REDIS_CONNECTION_STRING: ENC[AES256_GCM,data:h3rw59ijRSAMrEtLDjEZL5KfqpYJDH5JPx55nKXC8bjxPKirGO4adMb6rg41ACNw6n+n8lBzGZ4Um6qujNtftOmkZjPZng==,iv:Q2/G45u+o59bZr1PtFqP+zcgEI4pKf7hhOMF+qMbGvk=,tag:pGPAeNloJIkWwutlO53+0w==,type:str]
    APP_ADMIN_USER_LOGIN: ENC[AES256_GCM,data:QaHz8+zfnl6Z6klAL4dV,iv:cDRJBPX3/Fqv09NdM2TuthZDssUIJDYRNKSLVWpywG0=,tag:cUjDlMhzPeZGsroM/B2MdQ==,type:str]
    APP_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:ykAmXydNP0oDNDU/CVjYHh9KxrnTwkacgm4eRywMa4U=,iv:sH0WIFAFbRUTaMiXja7GZibhjOp7Qu7owthGyjuFypM=,tag:ZuvVnQvGSyVMJPm7b66cHw==,type:str]
    APP_ADMIN_USER_PID: ENC[AES256_GCM,data:EOFKl2USrLpBvOnb+0LDtZ1DtJZH1cv3qhU23F2XHundD10c,iv:gXjqx7Vo9LH28BU3/RiwlKUGs/EOGiVAnoLo1p3TyKE=,tag:DymlN4MNh2Uj1so3PG3Cig==,type:str]
    APP_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:rwcGVX/ervA8DCqruQR5pTeMgumirDR7Y9Y4VweDSeKjKkXcfTXRNA6rrA0mP5YJuuqyF0YPBXFNsr9qB15ZGE4cpEqo93lpvnon+49kp5KOH2z8OsepK90FTSQxHBCsuaJMEObdsqU4tbC6IEzWS0QZWNW+/77JjbmoDne8P52i/L3AiEmcPgy5xKp4CMlUpdDyaxZrkm13wHeU9VkmU3GEEke/QKSl9XsahSa0b4bo5Iis/idMLMF8umpvI+ydAkRw5IGWyMCfKSXLAIUBrhRgbUi3sscdlqYJClUHb02Sri0=,iv:LIhokA4L7Gz2am38nCOAi4OTbX4uuWWkTDzAhyFdxbY=,tag:u0QS4b0TNmCDVqlLYRIEbw==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN040d1UxUlkxdUJaeXN0
            N2ZRUURRYklXV0xhZGRUMVdFUXN6WmtHVnlRCnByb043SjRPdVNtMzFRaFZyVnY4
            MDBUK25qbCtvdVA2Uk5xQW1XbE9tNjQKLS0tIFBZQ2tISVRzVXduREFNMGxZOUZZ
            ZU9iaUZDdnlIM1dibHd6Q0RUdjRWemcKbJFC4rYLFnj42aJRrlxe9Vjp6CpWCQZD
            RS+TQ/1iXeNZ+MQEN9M6UyOCXmIFsh8k2o8rELupMJgWwitpQrIvxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T19:34:37Z"
    mac: ENC[AES256_GCM,data:3FsOh9CFrxn73TzpVyizAoCXnMvIeiuzHb9+tFawTJLnynFbTt9BYgNDIQ04F7F/FqkJ3NEqLVvvAZXWXA2OvKjyBbHJ+v0LJRWHYBqdDFGX8LXINi3gRGjLbzGXaAPFrnbQOKCQoGVyVesxT+f3sM16lNuOC0DQ54FsgAaljZ8=,iv:q8pjPYTLLlGakD6aapBUll9n4P274Q1Jpn1cDZH9Qck=,tag:qYRcLtmhWhE+mN0HOlgRqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
