secret:
    APP_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:A+mlxrEthbt0HO/JdyR4/MNDn14P1xx/lzlBDyeyrBI5i+77cpH9bChUP9/yLA==,iv:3aHu1dOVly1TCdfBvDKsRGsNvPxFxUYFIVQz16PuxIo=,tag:fJqj76hgJeACTa5wcsS2mw==,type:str]
    APP_POSTGRES_PASSWORD: ENC[AES256_GCM,data:822E/RcvgAVjetM=,iv:FmUmOqJ1j9T9J66jVig8BCY+b7ZiygTRR1J5qlRLlfw=,tag:Q9WJczqoCktMKu5CYZ+14w==,type:str]
    APP_REDIS_CONNECTION_STRING: ENC[AES256_GCM,data:zzrtOZkWbkI9UdtOyK0sPG24ioCKaJ3fbS+mOgxDYrXUAcSz2LyHaF4049M6M2Qpzxm1hJgZiZlPMQ09J9EmvnP9t0w+rQ==,iv:xjtGJNKThT7bk5y3x3MlwLfvVwHmFJAaofFnHHD2QdQ=,tag:lPw+Mn917PhzpDJMHX6Bmg==,type:str]
    APP_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:ykAmXydNP0oDNDU/CVjYHh9KxrnTwkacgm4eRywMa4U=,iv:sH0WIFAFbRUTaMiXja7GZibhjOp7Qu7owthGyjuFypM=,tag:ZuvVnQvGSyVMJPm7b66cHw==,type:str]
    APP_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:rwcGVX/ervA8DCqruQR5pTeMgumirDR7Y9Y4VweDSeKjKkXcfTXRNA6rrA0mP5YJuuqyF0YPBXFNsr9qB15ZGE4cpEqo93lpvnon+49kp5KOH2z8OsepK90FTSQxHBCsuaJMEObdsqU4tbC6IEzWS0QZWNW+/77JjbmoDne8P52i/L3AiEmcPgy5xKp4CMlUpdDyaxZrkm13wHeU9VkmU3GEEke/QKSl9XsahSa0b4bo5Iis/idMLMF8umpvI+ydAkRw5IGWyMCfKSXLAIUBrhRgbUi3sscdlqYJClUHb02Sri0=,iv:LIhokA4L7Gz2am38nCOAi4OTbX4uuWWkTDzAhyFdxbY=,tag:u0QS4b0TNmCDVqlLYRIEbw==,type:str]
    APP_E2E_TOKEN: ENC[AES256_GCM,data:DbWFOhIGSigr0nnKOM9+GoL3LMy9f5Ee1Tn+aa59BHT5FtI/SVCRb628cPk4Q+b863i8cBFVLpXngwIs1FyteS++N/ofYi7lVLl1sUsCv9LzhrGFvYA+shZF0yv4RRBAAtaIN3jwvZ46ou4Sc8cHstKfBkMc63zfINS3wXDjW0wVMrHxMipfnRahzA==,iv:IfiffHErgUN47CiU2tRGYc36quFTEQ5QTKD3au877kU=,tag:Mr79QOPJzHNbwZdJCKGVYA==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN040d1UxUlkxdUJaeXN0
            N2ZRUURRYklXV0xhZGRUMVdFUXN6WmtHVnlRCnByb043SjRPdVNtMzFRaFZyVnY4
            MDBUK25qbCtvdVA2Uk5xQW1XbE9tNjQKLS0tIFBZQ2tISVRzVXduREFNMGxZOUZZ
            ZU9iaUZDdnlIM1dibHd6Q0RUdjRWemcKbJFC4rYLFnj42aJRrlxe9Vjp6CpWCQZD
            RS+TQ/1iXeNZ+MQEN9M6UyOCXmIFsh8k2o8rELupMJgWwitpQrIvxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T18:09:00Z"
    mac: ENC[AES256_GCM,data:Hqo98M9RYit851z1iOsHPw4NKd+OASJjCO4zpCHb/bKpUzOflCogSUHDi99WloYP33AIl5SvdGvPOlgb/MvYfGHQGzga6V8sBIUurcareglufzXCgybx6SR4a26Jv+JkCEqO87J4PDjJGtG+d7nctENzf+oIHABES3uLx4xIwFg=,iv:DMvGyyb7x9vIzYEfrnuv11Fv/KLX+UNjqZezoYj8ihw=,tag:n3MhUwO3+rUqrZuGXgkM3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
