secret:
    APP_TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:A+mlxrEthbt0HO/JdyR4/MNDn14P1xx/lzlBDyeyrBI5i+77cpH9bChUP9/yLA==,iv:3aHu1dOVly1TCdfBvDKsRGsNvPxFxUYFIVQz16PuxIo=,tag:fJqj76hgJeACTa5wcsS2mw==,type:str]
    APP_POSTGRES_CONNECTION_STRING: ENC[AES256_GCM,data:oLeHFEwodKxVWcJgVsdn0t4zELJNj+By+D5u3tfvu5I54a0j4lU7onwtsV/Gg2YakQfGHeUAeKQtbpeZWOlza1O9GGv1pNa/to7T,iv:OjlfJ+o0FVbPFATHuZjixfE/mIC0VRTKuMamu+eZk48=,tag:hYz4RH4VCnoQ4M6Y8UyH5w==,type:str]
    APP_REDIS_CONNECTION_STRING: ENC[AES256_GCM,data:zzrtOZkWbkI9UdtOyK0sPG24ioCKaJ3fbS+mOgxDYrXUAcSz2LyHaF4049M6M2Qpzxm1hJgZiZlPMQ09J9EmvnP9t0w+rQ==,iv:xjtGJNKThT7bk5y3x3MlwLfvVwHmFJAaofFnHHD2QdQ=,tag:lPw+Mn917PhzpDJMHX6Bmg==,type:str]
    APP_ADMIN_USER_LOGIN: ENC[AES256_GCM,data:QaHz8+zfnl6Z6klAL4dV,iv:cDRJBPX3/Fqv09NdM2TuthZDssUIJDYRNKSLVWpywG0=,tag:cUjDlMhzPeZGsroM/B2MdQ==,type:str]
    APP_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:ykAmXydNP0oDNDU/CVjYHh9KxrnTwkacgm4eRywMa4U=,iv:sH0WIFAFbRUTaMiXja7GZibhjOp7Qu7owthGyjuFypM=,tag:ZuvVnQvGSyVMJPm7b66cHw==,type:str]
    APP_ADMIN_USER_PID: ENC[AES256_GCM,data:EOFKl2USrLpBvOnb+0LDtZ1DtJZH1cv3qhU23F2XHundD10c,iv:gXjqx7Vo9LH28BU3/RiwlKUGs/EOGiVAnoLo1p3TyKE=,tag:DymlN4MNh2Uj1so3PG3Cig==,type:str]
    APP_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:rwcGVX/ervA8DCqruQR5pTeMgumirDR7Y9Y4VweDSeKjKkXcfTXRNA6rrA0mP5YJuuqyF0YPBXFNsr9qB15ZGE4cpEqo93lpvnon+49kp5KOH2z8OsepK90FTSQxHBCsuaJMEObdsqU4tbC6IEzWS0QZWNW+/77JjbmoDne8P52i/L3AiEmcPgy5xKp4CMlUpdDyaxZrkm13wHeU9VkmU3GEEke/QKSl9XsahSa0b4bo5Iis/idMLMF8umpvI+ydAkRw5IGWyMCfKSXLAIUBrhRgbUi3sscdlqYJClUHb02Sri0=,iv:LIhokA4L7Gz2am38nCOAi4OTbX4uuWWkTDzAhyFdxbY=,tag:u0QS4b0TNmCDVqlLYRIEbw==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN040d1UxUlkxdUJaeXN0
            N2ZRUURRYklXV0xhZGRUMVdFUXN6WmtHVnlRCnByb043SjRPdVNtMzFRaFZyVnY4
            MDBUK25qbCtvdVA2Uk5xQW1XbE9tNjQKLS0tIFBZQ2tISVRzVXduREFNMGxZOUZZ
            ZU9iaUZDdnlIM1dibHd6Q0RUdjRWemcKbJFC4rYLFnj42aJRrlxe9Vjp6CpWCQZD
            RS+TQ/1iXeNZ+MQEN9M6UyOCXmIFsh8k2o8rELupMJgWwitpQrIvxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T19:34:28Z"
    mac: ENC[AES256_GCM,data:TA03IdYIrh69UspXOmhdDu1PsAZ3rTvZzhZDubc6TcT0QpzrDVtkb0l8QX63E5ngVSwA5HkKNBrtdtXQNvEo5U+Ijvulbm0dPoFQR+iPsPXMTPDL87tSAcjMy4lJO/hSvSxlVm5FoLGq7P9AJVLgEBFgM5yTgBhXFky+B2NAifU=,iv:WgVzTWUDQYO+5K8csfYiEODQFBnU5WHhot7VrOmFknc=,tag:tQqeZc7cbjj2f0BSGPtotA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
