apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.meta.name }}-server-header-api
  namespace: {{ .Values.meta.namespace }}
spec:
  headers:
    customResponseHeaders:
      Server: "{{ .Values.meta.name }}-api"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.meta.name }}-api-tls-cert
spec:
  secretName: {{ .Values.meta.name }}-api-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.api.host }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.meta.name }}-api-ingress-route
  namespace: {{ .Values.meta.namespace }}
spec:

  entryPoints:
    - web
    - websecure
  
  tls:
    secretName: {{ .Values.meta.name }}-api-tls-secret

  routes:

    - match: Host(`{{ .Values.ingress.api.host }}`) && (Method(`POST`) || Method(`PUT`) || Method(`PATCH`) || Method(`DELETE`))
      kind: Rule
      middlewares:
        - name: {{ .Values.meta.name }}-server-header-api
      services:
        - name: {{ .Values.meta.name }}-api-service
          port: 80

    - match: Host(`{{ .Values.ingress.api.host }}`) && (Method(`GET`) || Method(`OPTIONS`))
      kind: Rule
      middlewares:
        - name: {{ .Values.meta.name }}-server-header-api
      services:
        - name: {{ .Values.meta.name }}-api-service
          port: 80
          weight: 50
        - name: {{ .Values.meta.name }}-api-ro-service
          port: 80
          weight: 50

    - match: Host(`{{ .Values.ingress.api.host }}`) && PathPrefix(`{{ .Values.ingress.api.mirror_path }}`)
      kind: Rule
      middlewares:
        - name: {{ .Values.meta.name }}-replace-mirror-path
        - name: {{ .Values.meta.name }}-server-header-api
      services:
        - name: {{ .Values.meta.name }}-api-service
          port: 80
          weight: 50
        - name: {{ .Values.meta.name }}-api-ro-service
          port: 80
          weight: 50
