apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.meta.name }}-secret
  namespace: {{ .Values.meta.namespace }}
  annotations:
    helmwave.app/skip-diff: "true"
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
