runnerRegistrationToken: ENC[AES256_GCM,data:Mii6BNH7KdFOqQPZf2/9yhyj4wi5JnOgtaXAybI0fpCBQzR+sD/1UZHEcQkBkAgsuewqhajG06Jw3df36NznpPB9XTRS/xb+vw==,iv:KMjADAxM7a2H6NtAVIuDGJ/RgaEbnUSaQwaW6CLCjBk=,tag:OKfVEBkZ5RXau6V9z8+qyg==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZWdmM3psTGxQVThsTks2
            QWplaWdia3BlZ0VqTGlYd1NQRW85RTNKU1NZCkZOOEtNT3IyWVVoOXdJNE0wN3lP
            WEh3RnFxY212bXdRLzgwL0ZteCtXMmcKLS0tIFMrVTg4VWFyQm93SzlnVDNhaUls
            ZlJ3TzNNbVpyM3ZTYWRvdG9CR3pPYUkK+XbUBUPH4zx1E9wFoAM8YhhopkchBUSa
            SiGCdFVy1kVREHy2CBh0UwRKjK7sDjERutY4Ukw86BxAu744bSBR2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T06:34:59Z"
    mac: ENC[AES256_GCM,data:jbe3OcD/1tjG/ouBAXCfLj//PCyNxNAm+znfQjqDELwb7u9ySGONxfccpKa6rzHaSzySUf5ut9+6Hdu5fAOZ72kFRbdzFvlx5emUB+CT/5O1cQ+4UPG7l4m4HEzFeGqnHNPVu+X4bo+IjlJqddi9NOU65qAQG7n76xGjK3zJTSA=,iv:y8pRrB6ohvH2lEY/FwjLzecDauyaxq8J51W/nOPTmHQ=,tag:sFYzWU3/N188VLy7bfzezQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
