config:
    token: ENC[AES256_GCM,data:xXqEIDOjkOeTt+9W8YGMZ1HkZwPZPBktNGMjtRCY7N+cDlz/OKEh42VDuByqN830qwI9RsDU07SwTA==,iv:Qs4s9/I22QRIQdrb0bGRYoiOivnlUqDzFfB93fozlgM=,tag:uGoTtpNA4oWtrYJGm/eBwg==,type:str]
sops:
    age:
        - recipient: age18yxwsntjasphxzgtymdnrz2ggs2zd86rnyfpaeh2pk6gz42asgyqxd8r8a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMS9yYTJ6ekk5SWEwSjV2
            di8zTWxKa2o1bm1uYmZVaURINXFJV25KWWg0CnZEVmQzc3dUcEhRTkdNaEdEZHhC
            ckx4Q0kxZno2anVSTHlzOFNWWHVzZWcKLS0tIHI4bzBkL3ZyVkJuc0IrK3lrbmk0
            YWV4bHloWGdIdW1qMXcvY05mT0dQd2MKVzAKCdqErqIzR16r+S7dy13cyEbGXhOb
            wUTjNCOXeB6t/IvkfW0bhgQcY2DoKJH3IhXgBV6/CcUJxiNJkHJIjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T06:33:52Z"
    mac: ENC[AES256_GCM,data:Hg2dkA3OIr2Bi61amrbmumrYq2z/0Y8IXbdOmN3ay1rvvSYzi5/SRkdrZm5pZCfJj9AEro4+phery4xARODgyNH+3ARUiCJ/aclWiHh4sKtULRLW/Cni3EA9Jzv8crsiiR2/QBwPfFC/nkBMxK/+U2KRmXL6fUAgzVm9sntNMZE=,iv:eRfJKx9Ez4+cAy2abkEbUSI+gk1nHJQqzDbdUKXDTuE=,tag:lc6sdUDSxZL5PIZJ4NHxTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
