apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.meta.name }}-replace-path
  namespace: {{ .Values.meta.namespace }}
spec:
  replacePathRegex:
    regex: "^{{ .Values.ingress.api.path }}/(.*)"
    replacement: "/$1"
