apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.name }}-admin-service
  namespace: {{ .Values.meta.namespace }}
spec:
  selector:
    app: {{ .Values.meta.name }}-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
