apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.meta.name }}-admin-deployment
  namespace: {{ .Values.meta.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  replicas: {{ .Values.scaling.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.meta.name }}-admin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  template:
    metadata:
      namespace: {{ .Values.meta.namespace }}
      labels:
        app: {{ .Values.meta.name }}-admin
    spec:
      containers:
        - name: {{ .Values.meta.name }}-admin
          image: {{ .Values.image.repository }}/admin:{{ .Values.image.tag }}
          command: {{ .Values.image.command }}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /api/admin/config
              port: {{ .Values.port }}
              httpHeaders:
                - name: Host
                  value: {{ .Values.ingress.admin.host }}
            initialDelaySeconds: 15
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ .Values.meta.name }}-config
            - secretRef:
                name: {{ .Values.meta.name }}-secret
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
