apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.meta.name }}-gw-deployment
  namespace: {{ .Values.meta.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.meta.name }}-gw
  template:
    metadata:
      namespace: {{ .Values.meta.namespace }}
      labels:
        app: {{ .Values.meta.name }}-gw
    spec:
      containers:
        - name: {{ .Values.meta.name }}-gw
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: config-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: config-volume
              mountPath: /usr/share/nginx/html/management.html
              subPath: management.html
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.meta.name }}-gw-config
