apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.meta.name }}-gw-ingress
  namespace: {{ .Values.meta.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.ingress.gw.host }}
    secretName: {{ .Values.meta.name }}-gw-tls-cert
  rules:
    - host: {{ .Values.ingress.gw.host }}
      http:
        paths:
          - pathType: Prefix
            path: {{ .Values.ingress.gw.path }}
            backend:
              service:
                name: {{ .Values.meta.name }}-gw-service
                port:
                  number: 80
