apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.meta.name }}-migration-job
  namespace: {{ .Values.meta.namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.meta.name }}-migration
          image: {{ .Values.image.repository }}/migration:{{ .Values.image.tag }}
          command: ["./app", "up", "--database-url"]
          args: ["$(APP_POSTGRES_CONNECTION_STRING)"]
          envFrom:
            - configMapRef:
                name: {{ .Values.meta.name }}-config
            - secretRef:
                name: {{ .Values.meta.name }}-secret
