apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.name }}-postgres-service
  namespace: {{ .Values.meta.namespace }}
spec:
  selector:
    app: {{ .Values.meta.name }}-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
