apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.meta.name }}-redis-pvc
  namespace: {{ .Values.meta.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
